import { assertEquals } from "@std/assert";
import { part1, part2 } from "./main.ts";

const input = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`.trim();

Deno.test("part 1", () => {
  assertEquals(part1(input), 14);
});

Deno.test("part 2", () => {
  assertEquals(part2(input), 34);
});
